---
- name: Apply firewall rules
  ansible.builtin.import_playbook: firewall.yaml

- name: Setup Linux server
  ansible.builtin.import_playbook: linux_playbook.yaml

- name: Run automation role
  hosts: all
  roles:
    - role: plutoploy.automation.run
